apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: nueva-prueba
  title: Nueva Prueba
  description: veamos si funciona xd 
  tags:
    - js
    - awx
    - terraform
spec:
  owner: web@example.com
  templater: cra
  type: website
  path: '.'
  
  schema:
    required: 
      - component_id
      - use_jenkins
    properties:
      component_id:
        title: Name of job
        type: string
        description: nombre unico del componente. Usa minisculas
      description:
        title: Description
        type: string
        description: da una pequeña descripcion
      use_jenkins:
        title:  usa jenkins
        type: boolean
        description: incluir jenkins
        default: true